name: skills_53_regional_flutter
description: "A skills app"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  csv: ^5.0.0
  go_router: ^14.6.2
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/favicon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: monospace
      fonts:
        - asset: assets/fonts/monospace.ttf

  assets:
    - assets/data/
    - assets/data/about/1/
    - assets/data/about/2/
    - assets/data/about/3/
    - assets/data/about/4/
    - assets/data/about/5/
    - assets/data/about/
    - assets/
    - assets/icons/
